[package]
name = "enclave_host"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = {version = "0.61", features = [
    "Win32",
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Services",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
]}